namespace Sprint0
{
    // Contains various useful enumerations that are used throughout the code
    public static class Types
    {
        public enum Character { BAT, GEL, HAND, RED_GORIYA, SKELETON, ZOL, SNAKE, BLADE_TRAP, AQUAMENTUS, DODONGO, FLAME, OLDMAN}

        public enum Item { ARROW, BLUE_CANDLE, BLUE_POTION, BOMB, BOW, CLOCK, COMPASS, FAIRY, HEART, HEART_CONTAINER, 
        KEY, MAP, RUPEE, TRIFORCE_PIECE, WOODEN_BOOMERANG };

        public enum Block { WATER, BLUE_SAND, BLUE_STAIRS, BLUE_STATUE_LEFT, BLUE_STATUE_RIGHT, BLUE_TILE, BLUE_WALL, 
        GREY_BRICKS, LADDER, WHITE_BARS, PUSHABLE_BLOCK, BORDER_BLOCK, LEFT_DOOR_WAY_BLOCK, RIGHT_DOOR_WAY_BLOCK, ROOM_TRANSITION_BLOCK, EXIT_SECRET_TRANSITION_BLOCK};

        public enum Door { UP_LOCKED, RIGHT_LOCKED, DOWN_LOCKED, LEFT_LOCKED, 
                           UP_UNLOCKED, RIGHT_UNLOCKED, DOWN_UNLOCKED, LEFT_UNLOCKED,
                           UP_EVENT_LOCKED, RIGHT_EVENT_LOCKED, DOWN_EVENT_LOCKED, LEFT_EVENT_LOCKED,
                           UP_WALL, RIGHT_WALL, DOWN_WALL, LEFT_WALL,
                           UP_SECRET, RIGHT_SECRET, DOWN_SECRET, LEFT_SECRET}

        public enum Border { BLUE_BORDER, NONE}
        public enum Projectile { ARROW_EXPLOSION_PARTICLE, ARROW_PROJ, BLUE_ARROW_PROJ, BOMB_EXPLOSION_PARTICLE, BOMB_PROJ,
            BOSS_PROJ, DEATH_PARTICLE, FLAME_PROJ, BOOMERANG_PROJ, SWORD_MELEE, SWORD_PROJ, SWORD_FLAME_PROJ, SPAWN_PARTICLE };

        public enum Direction { UP, DOWN, LEFT, RIGHT, UPLEFT, UPRIGHT, DOWNLEFT, DOWNRIGHT, NO_DIRECTION }

        public enum RoomTransition { UP, DOWN, LEFT, RIGHT, SECRET };

        public enum Level{ LEVEL1 };
    }
}
